const DEFAULT_MOTIVATION_RULES = [
  {
    key: 'base_hour_rate',
    label: 'Первые часы',
    description: 'Ставка за час до порога переработки.',
    group: 'base',
    unit: 'currency',
    value: 250,
    sortOrder: 10,
  },
  {
    key: 'overtime_hour_rate',
    label: 'Переработка',
    description: 'Ставка за час после порога переработки.',
    group: 'base',
    unit: 'currency',
    value: 300,
    sortOrder: 20,
  },
  {
    key: 'overtime_after_hours',
    label: 'Порог переработки',
    description: 'После скольких часов включается повышенная ставка.',
    group: 'base',
    unit: 'hours',
    value: 12,
    sortOrder: 30,
  },
  {
    key: 'food_bonus_percent',
    label: 'Бонус с бара',
    description: 'Процент с продаж бара/кафе, если выполнен порог.',
    group: 'sales',
    unit: 'percent',
    value: 5,
    sortOrder: 40,
  },
  {
    key: 'food_bonus_threshold',
    label: 'Порог бара',
    description: 'Минимальная сумма продаж бара/кафе за день.',
    group: 'sales',
    unit: 'currency',
    value: 4000,
    sortOrder: 50,
  },
  {
    key: 'store_bonus_percent',
    label: 'Бонус с магазина',
    description: 'Процент с продаж товаров, кроме аренды.',
    group: 'sales',
    unit: 'percent',
    value: 3,
    sortOrder: 60,
  },
  {
    key: 'store_bonus_threshold',
    label: 'Порог магазина',
    description: 'Минимальная сумма продаж товаров за день.',
    group: 'sales',
    unit: 'currency',
    value: 3000,
    sortOrder: 70,
  },
  {
    key: 'vip_bonus_percent',
    label: 'VIP',
    description: 'Процент с VIP-услуг.',
    group: 'sales',
    unit: 'percent',
    value: 10,
    sortOrder: 80,
  },
  {
    key: 'chef_bonus_percent',
    label: 'Ракетка шефа',
    description: 'Процент с ракеток шефа, если выполнен порог по количеству.',
    group: 'sales',
    unit: 'percent',
    value: 5,
    sortOrder: 90,
  },
  {
    key: 'chef_quantity_threshold',
    label: 'Порог ракеток шефа',
    description: 'Минимальное количество ракеток шефа за день.',
    group: 'sales',
    unit: 'quantity',
    value: 8,
    sortOrder: 100,
  },
  {
    key: 'tubes_bonus_percent',
    label: 'Тубусы',
    description: 'Процент с тубусов, если выполнен порог по количеству.',
    group: 'sales',
    unit: 'percent',
    value: 10,
    sortOrder: 110,
  },
  {
    key: 'tubes_quantity_threshold',
    label: 'Порог тубусов',
    description: 'Минимальное количество тубусов за день.',
    group: 'sales',
    unit: 'quantity',
    value: 5,
    sortOrder: 120,
  },
];

module.exports = {
  DEFAULT_MOTIVATION_RULES,
};
